### ISSUE TITLE
how to add all json filds as objects?

### ISSUE THREAD

**Issue by ddkwork** [andydotxyz/notes#1]
err:

![err](https://user-images.githubusercontent.com/19886504/102045206-726d5280-3e13-11eb-88ac-128aa42b988f.jpg)

want:
 
![want](https://user-images.githubusercontent.com/19886504/102045239-80bb6e80-3e13-11eb-946c-16afece356ca.jpg)

 
 

src:
 
[awesomeProject.zip](https://github.com/andydotxyz/notes/files/5686264/awesomeProject.zip)

**Comment by andydotxyz** [comment]
I do not understand how this is a bug report against my notes app?
